@startuml er
title ER - Equipes

enum genero{
	masculino
	feminino
}

entity ligas {
	* id : uuid <<generated>>
	--
	* genero : genero
	* data_comeco : timestamp
	nome : text
	serie : text = A
	* criado_em : timestamp
	* atualizado_em : timestamp
}

entity equipes {
	* id : uuid <<generated>>
	--
	* nome : text
	url_brasao : text
	* id_ginasio : uuid <<FK>>  
	* apta : boolean = false
	descricao_aptidao : json
	* cidade: text
	* estado: text
	'min 12 per tournament'
	'max 22 per tounament'
	* criado_em : timestamp
	* atualizado_em : timestamp
}

entity ginasios {
	* id : uuid <<generated>>
	--
	* nome : text
	* cidade : text
	* estado : text
	* capacidade : integer
	* criado_em : timestamp
	* atualizado_em : timestamp
}

enum tipo_pessoa {
	tecnico 
	atleta
	arbitro
	auxiliares
	delegados
}

entity pessoas {
	* id : uuid <generated>>
	--
	* nome : text
	* documento : text <<UQ>>
	* genero : genero
	* data_nascimento : timestamp
	* documento_cbv : text
	* tipo : tipo_pessoa
	* criado_em : timestamp
	* atualizado_em : timestamp
}

enum posicoes {
	ponta
	oposto
	central
	libero
	levantador
}

enum partida_status {
	agendada
	em_andamento
	concluida
	cancelada
}

entity atletas{
	* id : uuid <<generated>>
	--
	* numero : tinyint
	* id_pessoa : uuid <<FK>>
	* id_equipe : uuid <<FK>>
	* criado_em : timestamp
	* atualizado_em : timestamp
}

entity tecnicos{
	* id : uuid <<generated>>
	--
	* documento_cref: text
	* id_pessoa: uuid <<FK>>
	* id_equipe : uuid <<FK>>
	* criado_em : timestamp
	* atualizado_em : timestamp
}

entity arbitros {
	* id : uuid <<generated>>
	--
	* id_pessoa : uuid <<FK>>
	* criado_em : timestamp
	* atualizado_em : timestamp
}

enum tipo_auxiliar {
	assistente_medico
	auxiliar_tecnico
	preparador_fisico
	fisioterapeuta
	medico
	massagista
}

entity auxiliares {
	* id : uuid <<generated>>
	--
	tipo : tipo_auxiliar
	* id_pessoa : uuid <<FK>>
	* id_equipe : uuid <<FK>>
	* criado_em : timestamp
	* atualizado_em : timestamp
}

entity delegados {
	* id : uuid <<generated>>
	--
	* id_pessoa: uuid <<FK>>
	* criado_em : timestamp
	* atualizado_em : timestamp
}

entity partidas {
	* id : uuid <<generated>>
	--
	* id_delegado : uuid <<FK>>
	* id_ginasio : uuid <<FK>>
	* status : partida_status
	* data_comeco : timestamp
	* data_finalizacao: timestamp
	* id_time_ganhador : uuid <<FK>>
	* data_criacao: timestamp
	* data_atualizacao: timestamp
}

entity equipes_partidas {
	* id : uuid <<generated>>
	--
	* id_equipe : uuid <<FK>>
	* id_partida : uuid <<FK>>
	* pontuacao: int = 0
	* sets_ganhos: int = 0
	* pontos_nos_sets: {quantidade: int}[] = []
	* sets_disputados: <<GENERATED>>
	* ganhou: smallint <<GENERATED>>
	resultado_cadastrado_em: timestamp
	* data_criacao: timestamp
	* data_atualizacao: timestamp
}

entity atletas_escalados {
	* id : uuid <<generated>>
	--
	* id_equipe_partida : uuid <<FK>>
	* id_atleta : uuid <<FK>>
	* posicao: posicao
	* data_criacao: timestamp
	* data_atualizacao: timestamp
}

enum tipo_arbitro {
	principal
	auxiliar
	quadra
}

entity arbitros_partida {
	* id : uuid <<generated>>
	--
	* id_arbitro : uuid <<FK>>
	* id_partida : uuid <<FK>>
	* tipo: tipo_arbitro
	* data_criacao: timestamp
	* data_atualizacao: timestamp
}

entity fundamentos_atletas {
	* id : uuid <<generated>>
	--
	* id_atleta_partida : uuid <<FK>>
	* bloqueios : int = 0
	* recepcoes : int = 0
	* aces : int = 0
	* saques : int = 0
	* ataques : int = 0
	* pontos : int = 0
	* data_criacao: timestamp
	* data_atualizacao: timestamp
}

entity pontuacoes_view {
	* idEquipe : uuid <<FK>>
	--
	* pontuacao : int
	* sets_ganhos : int
	* sets_disputados : int
	* sets_perdidos : int
	* pontos_average : int
	* sets_average : int
	* partidas_ganhas : int
	* partidas_perdidas : int
	* partidas_disputadas : int
}

entity melhores_liberos_view {
	* id_atleta : uuid <<FK>>
	--
	* recepcoes : int
}

ligas ||--o{ "0..12" equipes
ligas ||--o{ arbitros
ligas ||--o{ delegados
equipes ||--o{ "<= 22" atletas : no mínimo 12 para o time estar regular
equipes "1" --|| "1" tecnicos
equipes ||--o{ auxiliares
equipes ||-- ginasios
equipes ||-- pontuacoes_view
delegados "1" ||--o{ partidas
ginasios "1" ||--o{ partidas
partidas "1" ||--o{ "2" equipes_partidas : equipe mandante e visitante
partidas "1" ||--o{ "1..4" arbitros_partida 
equipes_partidas "1" ||--o{ "12..14" atletas_escalados : atletas que irão para a partida
atletas "1" ||--o{ atletas_escalados
atletas_escalados "1" ||--o{ fundamentos_atletas

atletas ||-- melhores_liberos_view


atletas ||-- pessoas
tecnicos ||-- pessoas
auxiliares ||-- pessoas
arbitros ||-- pessoas
delegados ||-- pessoas

@enduml